server:
  port: 8004 #指定运行端口
logging:
  level:
    root: INFO
  file:
    name: logs/${spring.cloud.client.ip-address}/${spring.application.name}.log
    path: logs
spring:
  application:
    name: spring-admin #指定服务名称
  security:
    user:
      name: admin
      password: YIpotfg8Z8TKA29ox
  thymeleaf:
    enabled: true
    cache: true
    encoding: UTF-8
    prefix: classpath:/templates/
    check-template-location: true
    mode: HTML
    suffix: .html
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}  #指定主机地址
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://admin:YIpotfg8Z8TKA29ox@eureka:8002/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
